Pandas documentation:
https://pd.pydata.org/docs/user_guide/

In [ ]:
import numpy as np
import pandas as pd

#### Creating DataFrame

In [ ]:
# Creating a DataFrame by passing a NumPy array, with a datetime index and labeled columns

dates = pd.date_range("2020-01-01", periods=6, freq='D')
print(f"dates:\n{dates}\n")

data = np.random.randn(6, 4) # numpy 6x4 matrix
print(f"data:\n{data}\n")

columns = list("ABCD")
print(f"columns:\n{columns}\n")

df = pd.DataFrame(data=data, index=dates, columns=columns)

df

dates:
DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

data:
[[-0.87889305  0.35227911  1.56159293 -0.85181358]
 [ 0.07344375 -2.08397853  0.10411743  0.24431931]
 [ 0.35118289 -0.69830979 -1.31708707  0.38756248]
 [-1.53111227  0.84602233 -0.71546575 -0.10597989]
 [-1.10293883 -0.71386896  0.45641968  2.28869315]
 [-0.23351083  1.01680504  0.25421617  0.73948461]]

columns:
['A', 'B', 'C', 'D']



A         B         C         D
2020-01-01 -0.878893  0.352279  1.561593 -0.851814
2020-01-02  0.073444 -2.083979  0.104117  0.244319
2020-01-03  0.351183 -0.698310 -1.317087  0.387562
2020-01-04 -1.531112  0.846022 -0.715466 -0.105980
2020-01-05 -1.102939 -0.713869  0.456420  2.288693
2020-01-06 -0.233511  1.016805  0.254216  0.739485

In [ ]:
# Creating a DataFrame by passing a dictionary of objects

df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20200101"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)

df2

A          B    C  D      E    F
0  1.0 2020-01-01  1.0  3   test  foo
1  1.0 2020-01-01  1.0  3  train  foo
2  1.0 2020-01-01  1.0  3   test  foo
3  1.0 2020-01-01  1.0  3  train  foo

#### Viewing data

In [ ]:
df.head(3)

A         B         C         D
2020-01-01 -0.878893  0.352279  1.561593 -0.851814
2020-01-02  0.073444 -2.083979  0.104117  0.244319
2020-01-03  0.351183 -0.698310 -1.317087  0.387562

In [ ]:
df.tail(3)

A         B         C         D
2020-01-04 -1.531112  0.846022 -0.715466 -0.105980
2020-01-05 -1.102939 -0.713869  0.456420  2.288693
2020-01-06 -0.233511  1.016805  0.254216  0.739485

In [ ]:
df.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [ ]:
df.to_numpy()

array([[-0.87889305,  0.35227911,  1.56159293, -0.85181358],
       [ 0.07344375, -2.08397853,  0.10411743,  0.24431931],
       [ 0.35118289, -0.69830979, -1.31708707,  0.38756248],
       [-1.53111227,  0.84602233, -0.71546575, -0.10597989],
       [-1.10293883, -0.71386896,  0.45641968,  2.28869315],
       [-0.23351083,  1.01680504,  0.25421617,  0.73948461]])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 6 entries, 2020-01-01 to 2020-01-06
Freq: D
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   A       6 non-null      float64
 1   B       6 non-null      float64
 2   C       6 non-null      float64
 3   D       6 non-null      float64
dtypes: float64(4)
memory usage: 240.0 bytes


In [ ]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.553638 -0.213508  0.057299  0.450378
std    0.731764  1.178172  0.994914  1.050203
min   -1.531112 -2.083979 -1.317087 -0.851814
25%   -1.046927 -0.709979 -0.510570 -0.018405
50%   -0.556202 -0.173015  0.179167  0.315941
75%   -0.003295  0.722587  0.405869  0.651504
max    0.351183  1.016805  1.561593  2.288693

#### Operations

In [ ]:
print(df)
print()
print(df.mean(axis='index')) # axis=0
print()
print(df.mean(axis='columns')) # axis=1

                   A         B         C         D
2020-01-01 -0.878893  0.352279  1.561593 -0.851814
2020-01-02  0.073444 -2.083979  0.104117  0.244319
2020-01-03  0.351183 -0.698310 -1.317087  0.387562
2020-01-04 -1.531112  0.846022 -0.715466 -0.105980
2020-01-05 -1.102939 -0.713869  0.456420  2.288693
2020-01-06 -0.233511  1.016805  0.254216  0.739485

A   -0.553638
B   -0.213508
C    0.057299
D    0.450378
dtype: float64

2020-01-01    0.045791
2020-01-02   -0.415525
2020-01-03   -0.319163
2020-01-04   -0.376634
2020-01-05    0.232076
2020-01-06    0.444249
Freq: D, dtype: float64


In [ ]:
# 1) vectorization
df["SUM"] = df[['A', 'B', 'C', 'D']].sum(axis='columns')
print(df)

# 2) using apply
df["SUM"] = df[['A', 'B', 'C', 'D']].apply(lambda row: sum(row), axis='columns')
print(df)

# 3) using iterrows (to be avoided)
for i, row in df[['A', 'B', 'C', 'D']].iterrows():
    row["SUM"] = sum(row)
print(df)



                   A         B         C         D       SUM
2020-01-01 -0.878893  0.352279  1.561593 -0.851814  0.183165
2020-01-02  0.073444 -2.083979  0.104117  0.244319 -1.662098
2020-01-03  0.351183 -0.698310 -1.317087  0.387562 -1.276651
2020-01-04 -1.531112  0.846022 -0.715466 -0.105980 -1.506536
2020-01-05 -1.102939 -0.713869  0.456420  2.288693  0.928305
2020-01-06 -0.233511  1.016805  0.254216  0.739485  1.776995
                   A         B         C         D       SUM
2020-01-01 -0.878893  0.352279  1.561593 -0.851814  0.183165
2020-01-02  0.073444 -2.083979  0.104117  0.244319 -1.662098
2020-01-03  0.351183 -0.698310 -1.317087  0.387562 -1.276651
2020-01-04 -1.531112  0.846022 -0.715466 -0.105980 -1.506536
2020-01-05 -1.102939 -0.713869  0.456420  2.288693  0.928305
2020-01-06 -0.233511  1.016805  0.254216  0.739485  1.776995
                   A         B         C         D       SUM
2020-01-01 -0.878893  0.352279  1.561593 -0.851814  0.183165
2020-01-02  0.073444 -2.

#### Slicing DataFrame

In [ ]:
df["A"]

2020-01-01   -0.878893
2020-01-02    0.073444
2020-01-03    0.351183
2020-01-04   -1.531112
2020-01-05   -1.102939
2020-01-06   -0.233511
Freq: D, Name: A, dtype: float64

In [ ]:
df.loc[:, ["A", "B"]]

A         B
2020-01-01 -0.878893  0.352279
2020-01-02  0.073444 -2.083979
2020-01-03  0.351183 -0.698310
2020-01-04 -1.531112  0.846022
2020-01-05 -1.102939 -0.713869
2020-01-06 -0.233511  1.016805

In [ ]:
df.loc["20200101":"20200102", ["A", "B"]] # both endpoints are included

A         B
2020-01-01 -0.878893  0.352279
2020-01-02  0.073444 -2.083979

In [ ]:
s = df.loc["20200101", ["A", "B"]] # reduction in the dimensions of the returned object: df --> series
print(type(s))
print(s)

<class 'pandas.core.series.Series'>
A   -0.878893
B    0.352279
Name: 2020-01-01 00:00:00, dtype: float64


In [ ]:
v = df.loc["20200101", "A"] # reduction in the dimensions of the returned object: df --> cell value
print(type(v))
print(v)

<class 'numpy.float64'>
-0.8788930539048423


In [ ]:
df[df["A"] > 0]

A         B         C         D       SUM
2020-01-02  0.073444 -2.083979  0.104117  0.244319 -1.662098
2020-01-03  0.351183 -0.698310 -1.317087  0.387562 -1.276651

In [ ]:
df[df["A"].between(0,1)]

A         B         C         D       SUM
2020-01-02  0.073444 -2.083979  0.104117  0.244319 -1.662098
2020-01-03  0.351183 -0.698310 -1.317087  0.387562 -1.276651

In [ ]:
filter_index = pd.date_range("20200101", periods=2, freq='2D')
print(filter_index)

df[df.index.isin(filter_index)]

DatetimeIndex(['2020-01-01', '2020-01-03'], dtype='datetime64[ns]', freq='2D')


A         B         C         D       SUM
2020-01-01 -0.878893  0.352279  1.561593 -0.851814  0.183165
2020-01-03  0.351183 -0.698310 -1.317087  0.387562 -1.276651

#### Setting values

In [ ]:
df['E'] = 1

df

A         B         C         D       SUM  E
2020-01-01 -0.878893  0.352279  1.561593 -0.851814  0.183165  1
2020-01-02  0.073444 -2.083979  0.104117  0.244319 -1.662098  1
2020-01-03  0.351183 -0.698310 -1.317087  0.387562 -1.276651  1
2020-01-04 -1.531112  0.846022 -0.715466 -0.105980 -1.506536  1
2020-01-05 -1.102939 -0.713869  0.456420  2.288693  0.928305  1
2020-01-06 -0.233511  1.016805  0.254216  0.739485  1.776995  1

In [ ]:
df.at["2020-01-01", "E"] = 0

df

A         B         C         D       SUM  E
2020-01-01 -0.878893  0.352279  1.561593 -0.851814  0.183165  0
2020-01-02  0.073444 -2.083979  0.104117  0.244319 -1.662098  1
2020-01-03  0.351183 -0.698310 -1.317087  0.387562 -1.276651  1
2020-01-04 -1.531112  0.846022 -0.715466 -0.105980 -1.506536  1
2020-01-05 -1.102939 -0.713869  0.456420  2.288693  0.928305  1
2020-01-06 -0.233511  1.016805  0.254216  0.739485  1.776995  1

In [ ]:
df.loc[df['A']>0, 'E'] = 1000

df

A         B         C         D       SUM     E
2020-01-01 -0.878893  0.352279  1.561593 -0.851814  0.183165     0
2020-01-02  0.073444 -2.083979  0.104117  0.244319 -1.662098  1000
2020-01-03  0.351183 -0.698310 -1.317087  0.387562 -1.276651  1000
2020-01-04 -1.531112  0.846022 -0.715466 -0.105980 -1.506536     1
2020-01-05 -1.102939 -0.713869  0.456420  2.288693  0.928305     1
2020-01-06 -0.233511  1.016805  0.254216  0.739485  1.776995     1

#### Missing data

In [ ]:
df = pd.DataFrame(
    {
        "col1": ["a", "b", np.nan, 3],
        "col2": [3, np.nan, np.nan, 5],
        "col3": [np.nan, np.nan, np.nan, np.nan]
    }
)

df

col1  col2  col3
0    a   3.0   NaN
1    b   NaN   NaN
2  NaN   NaN   NaN
3    3   5.0   NaN

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    3 non-null      object 
 1   col2    2 non-null      float64
 2   col3    0 non-null      float64
dtypes: float64(2), object(1)
memory usage: 224.0+ bytes


In [ ]:
# Warning! np.nan != np.nan
np.nan == np.nan

False

In [ ]:
None == None

True

In [ ]:
# To get the boolean mask where values are nan
pd.isna(df)

col1   col2  col3
0  False  False  True
1  False   True  True
2   True   True  True
3  False  False  True

In [ ]:
# To replace nan
df.fillna("AAA")

col1 col2 col3
0    a  3.0  AAA
1    b  AAA  AAA
2  AAA  AAA  AAA
3    3  5.0  AAA

In [ ]:
# To drop nan
df.dropna(how="any") # rows with at least one nan

Empty DataFrame
Columns: [col1, col2, col3]
Index: []

In [ ]:
df.dropna(how="all") # rows with only nan

col1  col2  col3
0    a   3.0   NaN
1    b   NaN   NaN
3    3   5.0   NaN

#### Merge

In [ ]:
df_left = pd.DataFrame(
    {
        "A": [1,2,3,4],
        "B": [5,6,7,8]
    }
)
print(f'df_left:\n{df_left}\n')

df_right = pd.DataFrame(
    {
        "C": [3,4,5,6],
        "D": [8,8,8,8]
    }
)
print(f'df_right:\n{df_right}\n')

for merge_mode in ['inner', 'left', 'right', 'outer']:
    print(f'merge {merge_mode}:')
    print(df_left.merge(df_right, left_on=['A'], right_on=['C'], how=merge_mode))
    print()

df_left:
   A  B
0  1  5
1  2  6
2  3  7
3  4  8

df_right:
   C  D
0  3  8
1  4  8
2  5  8
3  6  8

merge inner:
   A  B  C  D
0  3  7  3  8
1  4  8  4  8

merge left:
   A  B    C    D
0  1  5  NaN  NaN
1  2  6  NaN  NaN
2  3  7  3.0  8.0
3  4  8  4.0  8.0

merge right:
     A    B  C  D
0  3.0  7.0  3  8
1  4.0  8.0  4  8
2  NaN  NaN  5  8
3  NaN  NaN  6  8

merge outer:
     A    B    C    D
0  1.0  5.0  NaN  NaN
1  2.0  6.0  NaN  NaN
2  3.0  7.0  3.0  8.0
3  4.0  8.0  4.0  8.0
4  NaN  NaN  5.0  8.0
5  NaN  NaN  6.0  8.0



#### Grouping

In [ ]:
n_rows = 6
df = pd.DataFrame(
    {
        "Code": np.random.choice(["C1", "C2", "C3"], n_rows),
        "Type": np.random.choice(["good", "bad"], n_rows),
        "Value": np.random.randint(low=1, high=10, size=n_rows)
    }
)

df

Code  Type  Value
0   C3  good      4
1   C3   bad      8
2   C2  good      9
3   C2   bad      4
4   C2   bad      8
5   C1  good      2

In [ ]:
df.groupby(by=["Code", "Type"]).sum()

Value
Code Type       
C1   good      2
C2   bad      12
     good      9
C3   bad       8
     good      4

In [ ]:
df.groupby(by=["Code"]).sum()

Value
Code       
C1        2
C2       21
C3       12

In [ ]:
df.groupby(by=["Code"]).agg({'Type': ' '.join, 'Value': 'sum'})

Type  Value
Code                     
C1            good      2
C2    good bad bad     21
C3        good bad     12

#### Time series

#### Plotting

#### Getting data in/out